import { CanonicalGame } from '../../contracts/game';

// Re-export verified 313 GOG titles for mike.stokes85 matching https://www.gog.com/u/mike.stokes85/games
export { GOG_USER_LIBRARY } from './gogUserLibrary';

export const EPIC_USER_LIBRARY: CanonicalGame[] = [
  {
    id: 'epic-alan-wake-2',
    title: 'Alan Wake 2',
    sortTitle: 'Alan Wake 2',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-alan-wake-2',
        installed: false,
        playtimeMinutes: 840,
        lastPlayed: '2026-09-18T20:30:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-alanwake2-remedyentertainment-g1a-00-1920x1080-69ce535560b4.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-alanwake2-remedyentertainment-s2-1200x1600-09252efae033.jpg',
    shortDescription: 'Saga Anderson arrives to investigate ritualistic murders in Bright Falls. Alan Wake pens a dark story to shape the reality around him. Two heroes, two realities.',
    releaseDate: '27 Oct, 2023',
    developers: ['Remedy Entertainment'],
    publishers: ['Epic Games Publishing'],
    genres: ['Survival Horror', 'Psychological', 'Action'],
    tags: ['Survival Horror', 'Story Rich', 'Atmospheric', 'Single-player'],
    reviewSummary: {
      reviewScore: 9,
      reviewScoreDesc: 'Critically Acclaimed',
      totalPositive: 42000,
      totalNegative: 2100,
      totalReviews: 44100,
      positivePercent: 95,
    },
  },
  {
    id: 'epic-control',
    title: 'Control',
    sortTitle: 'Control',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-control',
        installed: false,
        playtimeMinutes: 920,
        lastPlayed: '2026-06-11T15:20:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-control-remedyentertainment-g1a-00-1920x1080-d02c7bcf7a6e.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-control-remedyentertainment-s2-1200x1600-f92d41fc6598.jpg',
    shortDescription: 'After a secretive agency in New York is invaded by an otherworldly threat, you become the new Director struggling to regain Control.',
    releaseDate: '27 Aug, 2019',
    developers: ['Remedy Entertainment'],
    publishers: ['505 Games'],
    genres: ['Action', 'Adventure', 'Supernatural'],
    tags: ['Third-Person Shooter', 'Female Protagonist', 'Supernatural'],
    reviewSummary: {
      reviewScore: 9,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 58000,
      totalNegative: 4900,
      totalReviews: 62900,
      positivePercent: 92,
    },
  },
  {
    id: 'steam-1190460', // Matches Death Stranding on Steam
    title: 'DEATH STRANDING',
    sortTitle: 'DEATH STRANDING',
    steamAppId: 1190460,
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-death-stranding',
        installed: false,
        playtimeMinutes: 1450,
        lastPlayed: '2026-07-02T19:00:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-deathstrandingdirectorscut-kojimaproductions-g1a-00-1920x1080-7389a9f244a0.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-deathstrandingdirectorscut-kojimaproductions-s2-1200x1600-754f2c0353df.jpg',
    shortDescription: 'From legendary game creator Hideo Kojima comes a genre-defying experience. Sam Bridges must brave a world utterly transformed by the Death Stranding.',
    releaseDate: '14 Jul, 2020',
    developers: ['KOJIMA PRODUCTIONS'],
    publishers: ['505 Games'],
    genres: ['Action', 'Adventure', 'Open World'],
    tags: ['Atmospheric', 'Open World', 'Story Rich', 'Sci-Fi'],
    reviewSummary: {
      reviewScore: 9,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 89000,
      totalNegative: 6800,
      totalReviews: 95800,
      positivePercent: 93,
    },
  },
  {
    id: 'epic-subnautica',
    title: 'Subnautica',
    sortTitle: 'Subnautica',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-subnautica',
        installed: false,
        playtimeMinutes: 1680,
        lastPlayed: '2026-08-30T11:45:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-subnautica-unknownworlds-g1a-00-1920x1080-1a7cb301bc6f.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-subnautica-unknownworlds-s2-1200x1600-1840efce23df.jpg',
    shortDescription: 'Descend into the depths of an alien underwater world filled with wonder and peril. Craft equipment, pilot submarines and out-smart wildlife.',
    releaseDate: '23 Jan, 2018',
    developers: ['Unknown Worlds Entertainment'],
    publishers: ['Unknown Worlds Entertainment'],
    genres: ['Open World Survival Craft', 'Underwater', 'Adventure'],
    tags: ['Survival', 'Underwater', 'Open World', 'Exploration'],
    reviewSummary: {
      reviewScore: 9,
      reviewScoreDesc: 'Overwhelmingly Positive',
      totalPositive: 240000,
      totalNegative: 8900,
      totalReviews: 248900,
      positivePercent: 96,
    },
  },
  {
    id: 'epic-fortnite',
    title: 'Fortnite',
    sortTitle: 'Fortnite',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-fortnite',
        installed: false,
        playtimeMinutes: 3200,
        lastPlayed: '2026-10-02T18:00:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/14br-consoles-1920x1080-wlogo-1920x1080-432974277.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-fortnite-s2-1200x1600.jpg',
    shortDescription: 'Create, play, and battle with friends for free in Fortnite. Be the last player standing in Battle Royale and Zero Build.',
    releaseDate: '21 Jul, 2017',
    developers: ['Epic Games'],
    publishers: ['Epic Games'],
    genres: ['Battle Royale', 'Shooter', 'Multiplayer'],
    tags: ['Multiplayer', 'Battle Royale', 'Free to Play', 'Cross-Platform'],
    reviewSummary: {
      reviewScore: 8,
      reviewScoreDesc: 'Positive',
      totalPositive: 950000,
      totalNegative: 120000,
      totalReviews: 1070000,
      positivePercent: 88,
    },
  },
  {
    id: 'epic-gta-v',
    title: 'Grand Theft Auto V',
    sortTitle: 'Grand Theft Auto V',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-gta-v',
        installed: false,
        playtimeMinutes: 4500,
        lastPlayed: '2026-09-08T22:15:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-gta-v-rockstargames-g1a-00-1920x1080-327883441.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-gta-v-rockstargames-s2-1200x1600-412239485.jpg',
    shortDescription: 'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with the criminal underworld.',
    releaseDate: '14 Apr, 2015',
    developers: ['Rockstar North'],
    publishers: ['Rockstar Games'],
    genres: ['Open World', 'Action', 'Multiplayer'],
    tags: ['Open World', 'Action', 'Multiplayer', 'Crime'],
    reviewSummary: {
      reviewScore: 9,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 1450000,
      totalNegative: 180000,
      totalReviews: 1630000,
      positivePercent: 89,
    },
  },
  {
    id: 'steam-1145360', // Hades
    title: 'Hades',
    sortTitle: 'Hades',
    steamAppId: 1145360,
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-hades',
        installed: false,
        playtimeMinutes: 2150,
        lastPlayed: '2026-08-14T19:20:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-hades-supergiantgames-g1a-00-1920x1080-605893248.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-hades-supergiantgames-s2-1200x1600-745239120.jpg',
    shortDescription: 'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion.',
    releaseDate: '17 Sep, 2020',
    developers: ['Supergiant Games'],
    publishers: ['Supergiant Games'],
    genres: ['Action Roguelike', 'Hack and Slash', 'Indie'],
    tags: ['Action Roguelike', 'Indie', 'Mythology', 'Great Soundtrack'],
    reviewSummary: {
      reviewScore: 10,
      reviewScoreDesc: 'Overwhelmingly Positive',
      totalPositive: 230000,
      totalNegative: 4100,
      totalReviews: 234100,
      positivePercent: 98,
    },
  },
  {
    id: 'epic-borderlands-3',
    title: 'Borderlands 3',
    sortTitle: 'Borderlands 3',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-borderlands-3',
        installed: false,
        playtimeMinutes: 1350,
        lastPlayed: '2026-05-19T21:00:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-borderlands3-gearbox-g1a-00-1920x1080-584739201.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-borderlands3-gearbox-s2-1200x1600-473829103.jpg',
    shortDescription: 'The original shooter-looter returns, packing bazillions of guns and a mayhem-fueled adventure! Blast through new worlds and enemies.',
    releaseDate: '13 Sep, 2019',
    developers: ['Gearbox Software'],
    publishers: ['2K'],
    genres: ['Action', 'RPG', 'Looter Shooter'],
    tags: ['Looter Shooter', 'Co-op', 'FPS', 'Action RPG'],
    reviewSummary: {
      reviewScore: 8,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 110000,
      totalNegative: 22000,
      totalReviews: 132000,
      positivePercent: 83,
    },
  },
  {
    id: 'epic-dead-cells',
    title: 'Dead Cells',
    sortTitle: 'Dead Cells',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-dead-cells',
        installed: false,
        playtimeMinutes: 1820,
        lastPlayed: '2026-07-28T16:40:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-deadcells-motiontwin-g1a-00-1920x1080-482910283.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-deadcells-motiontwin-s2-1200x1600-583920192.jpg',
    shortDescription: 'Dead Cells is a rogue-lite, metroidvania inspired, action-platformer. You will explore a sprawling, ever-changing castle.',
    releaseDate: '7 Aug, 2018',
    developers: ['Motion Twin'],
    publishers: ['Motion Twin'],
    genres: ['Action Roguelike', 'Metroidvania', 'Platformer'],
    tags: ['Rogue-lite', 'Pixel Graphics', 'Metroidvania', 'Souls-like'],
    reviewSummary: {
      reviewScore: 10,
      reviewScoreDesc: 'Overwhelmingly Positive',
      totalPositive: 140000,
      totalNegative: 4500,
      totalReviews: 144500,
      positivePercent: 97,
    },
  },
  {
    id: 'epic-prey',
    title: 'Prey',
    sortTitle: 'Prey',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-prey',
        installed: false,
        playtimeMinutes: 980,
        lastPlayed: '2026-06-04T14:10:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-prey-arkane-g1a-00-1920x1080-384910293.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-prey-arkane-s2-1200x1600-294819203.jpg',
    shortDescription: 'In Prey, you awaken aboard Talos I, a space station orbiting the moon in the year 2032. You are the key subject of an experiment meant to alter humanity.',
    releaseDate: '5 May, 2017',
    developers: ['Arkane Studios'],
    publishers: ['Bethesda Softworks'],
    genres: ['Immersive Sim', 'Sci-Fi', 'FPS'],
    tags: ['Immersive Sim', 'Sci-Fi', 'Atmospheric', 'Single-player'],
    reviewSummary: {
      reviewScore: 9,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 38000,
      totalNegative: 3400,
      totalReviews: 41400,
      positivePercent: 91,
    },
  },
  {
    id: 'epic-civilization-vi',
    title: "Sid Meier's Civilization VI",
    sortTitle: "Civilization VI",
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-civilization-vi',
        installed: false,
        playtimeMinutes: 2890,
        lastPlayed: '2026-09-02T23:00:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-civ6-firaxis-g1a-00-1920x1080-482910392.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-civ6-firaxis-s2-1200x1600-482910392.jpg',
    shortDescription: 'Civilization VI offers new ways to engage with your world: cities now physically expand across the map, active research in technology unlocks new potential.',
    releaseDate: '21 Oct, 2016',
    developers: ['Firaxis Games'],
    publishers: ['2K'],
    genres: ['Strategy', '4X', 'Turn-Based'],
    tags: ['4X', 'Strategy', 'Turn-Based', 'Historical'],
    reviewSummary: {
      reviewScore: 8,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 215000,
      totalNegative: 45000,
      totalReviews: 260000,
      positivePercent: 83,
    },
  },
  {
    id: 'epic-dishonored',
    title: 'Dishonored - Definitive Edition',
    sortTitle: 'Dishonored - Definitive Edition',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-dishonored',
        installed: false,
        playtimeMinutes: 760,
        lastPlayed: '2026-04-12T19:30:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-dishonored-arkane-g1a-00-1920x1080-283910293.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-dishonored-arkane-s2-1200x1600-384910293.jpg',
    shortDescription: 'Dishonored is an immersive first-person action game that casts you as a supernatural assassin driven by revenge. Creatively eliminate your targets.',
    releaseDate: '9 Oct, 2012',
    developers: ['Arkane Studios'],
    publishers: ['Bethesda Softworks'],
    genres: ['Stealth', 'Action', 'Immersive Sim'],
    tags: ['Stealth', 'First-Person', 'Atmospheric', 'Immersive Sim'],
    reviewSummary: {
      reviewScore: 10,
      reviewScoreDesc: 'Overwhelmingly Positive',
      totalPositive: 78000,
      totalNegative: 2100,
      totalReviews: 80100,
      positivePercent: 97,
    },
  },
  {
    id: 'epic-star-wars-battlefront-2',
    title: 'STAR WARS Battlefront II: Celebration Edition',
    sortTitle: 'STAR WARS Battlefront II: Celebration Edition',
    platforms: [
      {
        platformId: 'epic',
        platformGameId: 'epic-swbf2',
        installed: false,
        playtimeMinutes: 1250,
        lastPlayed: '2026-07-18T20:00:00Z',
      },
    ],
    headerImage: 'https://cdn2.unrealengine.com/egs-swbf2-dice-g1a-00-1920x1080-283910293.jpg',
    capsuleImage: 'https://cdn2.unrealengine.com/egs-swbf2-dice-s2-1200x1600-384910293.jpg',
    shortDescription: 'Be the hero in the ultimate STAR WARS battle fantasy with STAR WARS Battlefront II: Celebration Edition! Master heroes, starfighters and troopers.',
    releaseDate: '17 Nov, 2017',
    developers: ['DICE'],
    publishers: ['Electronic Arts'],
    genres: ['Shooter', 'Action', 'Sci-Fi'],
    tags: ['Sci-Fi', 'Multiplayer', 'Shooter', 'Space'],
    reviewSummary: {
      reviewScore: 8,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 65000,
      totalNegative: 9800,
      totalReviews: 74800,
      positivePercent: 86,
    },
  },
];

export const XBOX_USER_LIBRARY: CanonicalGame[] = [
  {
    id: 'xbox-halo-infinite',
    title: 'Halo Infinite',
    sortTitle: 'Halo Infinite',
    platforms: [
      {
        platformId: 'xbox',
        platformGameId: 'xbox-halo-infinite',
        installed: false,
        playtimeMinutes: 1100,
        lastPlayed: '2026-08-14T21:00:00Z',
      },
    ],
    headerImage: 'https://store-images.s-microsoft.com/image/apps.21536.13727851868390641.c11e64cf-2d3a-4424-9b2f-99f8d91c7a85.8e4c0792-6229-411a-a63e-6d43e2646d6a',
    capsuleImage: 'https://store-images.s-microsoft.com/image/apps.21536.13727851868390641.c11e64cf-2d3a-4424-9b2f-99f8d91c7a85.8e4c0792-6229-411a-a63e-6d43e2646d6a',
    shortDescription: 'When all hope is lost and humanity’s fate hangs in the balance, Master Chief is ready to confront the most ruthless foe he’s ever faced on Zeta Halo.',
    releaseDate: '8 Dec, 2021',
    developers: ['343 Industries'],
    publishers: ['Xbox Game Studios'],
    genres: ['FPS', 'Action', 'Sci-Fi'],
    tags: ['FPS', 'Multiplayer', 'Sci-Fi', 'First-Person'],
    reviewSummary: {
      reviewScore: 7,
      reviewScoreDesc: 'Mostly Positive',
      totalPositive: 160000,
      totalNegative: 45000,
      totalReviews: 205000,
      positivePercent: 78,
    },
  },
  {
    id: 'xbox-forza-horizon-5',
    title: 'Forza Horizon 5',
    sortTitle: 'Forza Horizon 5',
    platforms: [
      {
        platformId: 'xbox',
        platformGameId: 'xbox-forza-horizon-5',
        installed: false,
        playtimeMinutes: 2450,
        lastPlayed: '2026-09-24T17:15:00Z',
      },
    ],
    headerImage: 'https://store-images.s-microsoft.com/image/apps.43952.13727851868390641.a5b3f124-7e8c-4a11-85b4-d54b6d412d09.f8b3c104-5182-4bb3-bc52-19e48b301c22',
    capsuleImage: 'https://store-images.s-microsoft.com/image/apps.43952.13727851868390641.a5b3f124-7e8c-4a11-85b4-d54b6d412d09.f8b3c104-5182-4bb3-bc52-19e48b301c22',
    shortDescription: 'Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action.',
    releaseDate: '9 Nov, 2021',
    developers: ['Playground Games'],
    publishers: ['Xbox Game Studios'],
    genres: ['Racing', 'Open World', 'Driving'],
    tags: ['Racing', 'Open World', 'Multiplayer', 'Automobile Sim'],
    reviewSummary: {
      reviewScore: 9,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 145000,
      totalNegative: 18000,
      totalReviews: 163000,
      positivePercent: 89,
    },
  },
  {
    id: 'xbox-gears-5',
    title: 'Gears 5',
    sortTitle: 'Gears 5',
    platforms: [
      {
        platformId: 'xbox',
        platformGameId: 'xbox-gears-5',
        installed: false,
        playtimeMinutes: 780,
        lastPlayed: '2026-06-19T22:00:00Z',
      },
    ],
    headerImage: 'https://store-images.s-microsoft.com/image/apps.34212.13727851868390641.b24c8851-9e23-455b-9d41-118c66e2c34d.e21b0682-1082-4299-8cfb-665e729ba9bc',
    capsuleImage: 'https://store-images.s-microsoft.com/image/apps.34212.13727851868390641.b24c8851-9e23-455b-9d41-118c66e2c34d.e21b0682-1082-4299-8cfb-665e729ba9bc',
    shortDescription: 'From one of gaming’s most acclaimed sagas, Gears is bigger than ever. With all-out war descending, Kait Diaz breaks away to uncover her connection to the enemy.',
    releaseDate: '10 Sep, 2019',
    developers: ['The Coalition'],
    publishers: ['Xbox Game Studios'],
    genres: ['Action', 'Third-Person Shooter', 'Co-op'],
    tags: ['Third-Person Shooter', 'Action', 'Gore', 'Co-op'],
    reviewSummary: {
      reviewScore: 7,
      reviewScoreDesc: 'Mostly Positive',
      totalPositive: 32000,
      totalNegative: 9800,
      totalReviews: 41800,
      positivePercent: 77,
    },
  },
  {
    id: 'xbox-sea-of-thieves',
    title: 'Sea of Thieves',
    sortTitle: 'Sea of Thieves',
    platforms: [
      {
        platformId: 'xbox',
        platformGameId: 'xbox-sea-of-thieves',
        installed: false,
        playtimeMinutes: 1890,
        lastPlayed: '2026-09-05T20:45:00Z',
      },
    ],
    headerImage: 'https://store-images.s-microsoft.com/image/apps.52189.13727851868390641.f50f4a4d-0453-4889-9b51-739c36279f10.1fa8e5b5-7c05-4c07-b286-90e666993cbe',
    capsuleImage: 'https://store-images.s-microsoft.com/image/apps.52189.13727851868390641.f50f4a4d-0453-4889-9b51-739c36279f10.1fa8e5b5-7c05-4c07-b286-90e666993cbe',
    shortDescription: 'Sea of Thieves offers the essential pirate experience, from sailing and fighting to exploring and looting – everything you need to live the pirate life and become a legend.',
    releaseDate: '20 Mar, 2018',
    developers: ['Rare Ltd'],
    publishers: ['Xbox Game Studios'],
    genres: ['Pirates', 'Open World', 'Multiplayer'],
    tags: ['Pirates', 'Multiplayer', 'Open World', 'Co-op', 'Adventure'],
    reviewSummary: {
      reviewScore: 9,
      reviewScoreDesc: 'Very Positive',
      totalPositive: 280000,
      totalNegative: 31000,
      totalReviews: 311000,
      positivePercent: 90,
    },
  },
];
